apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 0
  template:
    spec:
      serviceAccountName: ''
      containers:
        - name: code
          image: 'public.ecr.aws/risken/code/code:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitleaks
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 0
  template:
    spec:
      serviceAccountName: ''
      containers:
        - name: gitleaks
          image: 'public.ecr.aws/risken/code/gitleaks:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''

---
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code
  namespace: code
