apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: code
          image: 'public.ecr.aws/risken/code/code:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'FALSE'
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: 'xray-service.amazon-cloudwatch:2000'
            - name: ENV_NAME
              value: 'eks'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitleaks
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: gitleaks
          image: 'public.ecr.aws/risken/code/gitleaks:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'FALSE'
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: 'xray-service.amazon-cloudwatch:2000'
            - name: ENV_NAME
              value: 'eks'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitleaks-full-scan
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: gitleaks-full-scan
          image: 'public.ecr.aws/risken/code/gitleaks:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'FALSE'
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: 'xray-service.amazon-cloudwatch:2000'
            - name: ENV_NAME
              value: 'eks'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
