apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: ''
      containers:
        - name: gateway
          image: 'public.ecr.aws/risken/gateway/gateway:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'FALSE'
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: 'xray-service.amazon-cloudwatch:2000'
            - name: ENV_NAME
              value: 'eks'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: gateway
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: ''
      containers:
        - name: web
          image: 'public.ecr.aws/risken/gateway/web:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m

---
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: gateway
