commonLabels:
  env: local
commonAnnotations:
  note: local
bases:
  - ../../base
  - ../../middleware
patchesStrategicMerge:
  - gateway.yaml
  - core.yaml
  - aws.yaml
  - osint.yaml
  - diagnosis.yaml
  - code.yaml
  - google.yaml
  - middleware.yaml
