apiVersion: apps/v1
kind: Deployment
metadata:
  name: portscan
  namespace: diagnosis
  labels:
    app: portscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portscan
  template:
    metadata:
      labels:
        app: portscan
    spec:
      serviceAccountName: diagnosis
      containers:
        - name: portscan
          image: 'public.ecr.aws/risken/diagnosis/portscan:latest'
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 400Mi
              cpu: 500m
          ports:
            - containerPort: 19004
              name: portscan
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/diagnosis/portscan'
