apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnosis-wpscan
  namespace: risken
  labels:
    app: diagnosis-wpscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnosis-wpscan
  template:
    metadata:
      labels:
        app: diagnosis-wpscan
    spec:
      serviceAccountName: risken
      containers:
        - name: diagnosis-wpscan
          image: 'public.ecr.aws/risken/diagnosis/wpscan:latest'
          resources:
            limits:
              memory: 800Mi
              cpu: 800m
            requests:
              memory: 600Mi
              cpu: 600m
          ports:
            - containerPort: 19003
              name: wpscan
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/diagnosis/wpscan'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
