apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: core
  labels:
    app: core
spec:
  clusterIP: None
  selector:
    app: core
  ports:
    - name: core
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: datasource-api
  namespace: core
  labels:
    app: datasource-api
spec:
  clusterIP: None
  selector:
    app: datasource-api
  ports:
    - name: datasource-api
      protocol: TCP
      port: 8081
      targetPort: 8081
