apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitleaks
  namespace: code
  labels:
    app: gitleaks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitleaks
  template:
    metadata:
      labels:
        app: gitleaks
    spec:
      serviceAccountName: code
      containers:
        - name: gitleaks
          image: 'public.ecr.aws/risken/code/gitleaks:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 1
            requests:
              memory: 200Mi
              cpu: 600m
          ports:
            - containerPort: 10002
              name: gitleaks
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/code/gitleaks'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
