apiVersion: apps/v1
kind: Deployment
metadata:
  name: google
  namespace: google
  labels:
    app: google
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google
  template:
    metadata:
      labels:
        app: google
    spec:
      serviceAccountName: google
      containers:
        - name: google
          image: 'public.ecr.aws/risken/google/google:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 11001
              name: google
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/google/google'
