apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitleaks
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gitleaks
          image: 'public.ecr.aws/risken/code/gitleaks:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: code-gitleaks-properties
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency
  namespace: code
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dependency
          image: 'public.ecr.aws/risken/code/dependency:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: code-dependency-properties
