apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpscan
  namespace: diagnosis
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wpscan
          image: 'public.ecr.aws/risken/diagnosis/wpscan:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: diagnosis-wpscan-properties

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portscan
  namespace: diagnosis
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: portscan
          image: 'public.ecr.aws/risken/diagnosis/portscan:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: diagnosis-portscan-properties

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationscan
  namespace: diagnosis
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: diagnosis
      containers:
        - name: applicationscan
          image: 'public.ecr.aws/risken/diagnosis/applicationscan:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: diagnosis-applicationscan-properties
