apiVersion: apps/v1
kind: Deployment
metadata:
  name: subdomain
  namespace: osint
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: subdomain
          image: 'public.ecr.aws/risken/osint/subdomain:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: osint-subdomain-properties

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: osint
  labels:
    version: "latest"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: website
          image: 'public.ecr.aws/risken/osint/website:latest'
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: AWS_DEFAULT_REGION
              value: 'ap-northeast-1'
            - name: ENV_INJECTOR_META_CONFIG
              value: ''
          envFrom:
          - configMapRef:
              name: osint-website-properties
