apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: report-cronjob
  namespace: core
  labels:
    app: report
spec:
  # The time zone must be set in UTC.(For JST, set +0900)
  # @see https://kubernetes.io/ja/docs/concepts/workloads/controllers/cron-jobs/ 
  schedule: "00 15 * * *" 
  jobTemplate:
    metadata:
      labels:
        app: report
    spec:
      template:
        spec:
          serviceAccountName: core
          containers:
          - name: report-cronjob
            image: alpine
            resources:
              limits:
                memory: 400Mi
                cpu: 200m
              requests:
                memory: 200Mi
                cpu: 100m
            command: ["sh", "-c"]
            args:
            - cd /tmp;
              wget -q https://github.com/fullstorydev/grpcurl/releases/download/v1.8.2/grpcurl_1.8.2_linux_arm64.tar.gz;
              tar xvfz grpcurl_1.8.2_linux_arm64.tar.gz;
              /tmp/grpcurl -plaintext report.core.svc.cluster.local:8005 core.report.ReportService.CollectReportFinding;
          restartPolicy: Never
