apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: middleware
spec:
  type: NodePort
  selector:
    app: metabase
  ports:
  - name: metabase
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metabase
  name: metabase
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        resources:
          limits:
            memory: 800Mi
            cpu: 200m
          requests:
            memory: 400Mi
            cpu: 100m
        ports:
        - containerPort: 3000
          protocol: TCP
        # env:
        # - name: MB_DB_TYPE
        #   value: 'mysql'
        # - name: MB_DB_DBNAME
        #   value: 'mimosa'
        # - name: MB_DB_HOST
        #   value: 'db.middleware.svc.cluster.local'
        # - name: MB_DB_PORT
        #   value: '3306'
        # - name: MB_DB_USER
        #   value: 'hoge'
        # - name: MB_DB_PASS
        #   value: 'moge'
        # - name: MB_ENCRYPTION_SECRET_KEY
        #   value: 'pelease change key with openssl rand-base64 32'
