apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mimosa-db
  namespace: middleware
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mimosa-db
  namespace: middleware
  labels:
    type: local
spec:
  storageClassName: mimosa-db
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/mysql
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: middleware
  name: mimosa-db-pvc
spec:
  storageClassName: mimosa-db
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
