apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: middleware
  labels:
    app: db
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
