apiVersion: batch/v1
kind: CronJob
metadata:
  name: code-cronjob
  namespace: code
  labels:
    app: code
spec:
  # The time zone must be set in UTC.(For JST, set +0900)
  # @see https://kubernetes.io/ja/docs/concepts/workloads/controllers/cron-jobs/ 
  schedule: "15 17 * * *" 
  jobTemplate:
    metadata:
      labels:
        app: code
    spec:
      template:
        spec:
          serviceAccountName: code
          containers:
          - name: code-cronjob
            image: alpine
            resources:
              limits:
                memory: 400Mi
                cpu: 200m
              requests:
                memory: 200Mi
                cpu: 100m
            command: ["sh", "-c"]
            args:
            - cd /tmp;
              wget -q https://github.com/fullstorydev/grpcurl/releases/download/v1.8.2/grpcurl_1.8.2_linux_arm64.tar.gz;
              tar xvfz grpcurl_1.8.2_linux_arm64.tar.gz;
              /tmp/grpcurl -plaintext code.code.svc.cluster.local:10001 code.code.CodeService.InvokeScanAllGitleaks;
          restartPolicy: Never
