apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
  namespace: code
  labels:
    app: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      serviceAccountName: code
      containers:
        - name: code
          image: 'public.ecr.aws/risken/code/code:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 10001
              name: code
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/code/code'
