apiVersion: v1
kind: Service
metadata:
  name: code
  namespace: code
  labels:
    app: code
spec:
  clusterIP: None
  selector:
    app: code
  ports:
    - name: code
      protocol: TCP
      port: 10001
      targetPort: 10001
