apiVersion: apps/v1
kind: Deployment
metadata:
  name: portscan
  namespace: google
  labels:
    app: portscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portscan
  template:
    metadata:
      labels:
        app: portscan
    spec:
      serviceAccountName: google
      containers:
        - name: portscan
          image: 'public.ecr.aws/risken/google/portscan:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 11005
              name: portscan
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/google/portscan'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
