apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc
  namespace: google
  labels:
    app: scc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc
  template:
    metadata:
      labels:
        app: scc
    spec:
      serviceAccountName: google
      containers:
        - name: scc
          image: 'public.ecr.aws/risken/google/scc:latest'
          resources:
            limits:
              memory: 800Mi
              cpu: 1
            requests:
              memory: 500Mi
              cpu: 600m
          ports:
            - containerPort: 11004
              name: scc
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/google/scc'
