apiVersion: v1
kind: Service
metadata:
  name: project
  namespace: core
  labels:
    app: project
spec:
  clusterIP: None
  selector:
    app: project
  ports:
    - name: project
      protocol: TCP
      port: 8003
      targetPort: 8003
