apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: risken
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: risken
      containers:
        - name: web
          image: 'public.ecr.aws/risken/gateway/web:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 80
              name: web
