apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: risken
  # labels:
  #   app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
