apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasource-api
  namespace: datasource
  labels:
    app: datasource-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasource-api
  template:
    metadata:
      labels:
        app: datasource-api
    spec:
      serviceAccountName: datasource
      containers:
        - name: datasource-api
          image: 'public.ecr.aws/risken/risken-datasource-api:latest'
          resources:
            limits:
              memory: 2048Mi
              cpu: 1
            requests:
              memory: 200Mi
              cpu: 100m
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8081
              name: datasource-api
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/datasource-api'
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
          readinessProbe:
            grpc:
              port: 8081
            initialDelaySeconds: 5
