apiVersion: v1
kind: Service
metadata:
  name: datasource-api
  namespace: datasource
  labels:
    app: datasource-api
spec:
  clusterIP: None
  selector:
    app: datasource-api
  ports:
    - name: datasource-api
      protocol: TCP
      port: 8081
      targetPort: 8081
