apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: risken
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: risken
      containers:
        - name: gateway
          image: 'public.ecr.aws/risken/gateway/gateway:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 8000
              name: gateway
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/gateway/gateway'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
