apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: risken
  # labels:
  #   app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
