apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alert-cronjob
  namespace: core
  labels:
    app: alert-cronjob
spec:
  schedule: "00 01 * * *"
  jobTemplate:
    metadata:
      labels:
        app: alert-cronjob
    spec:
      template:
        spec:
          serviceAccountName: core
          containers:
          - name: alert-cronjob
            image: alpine
            resources:
              limits:
                memory: 400Mi
                cpu: 200m
              requests:
                memory: 200Mi
                cpu: 100m
            command: ["sh", "-c"]
            args:
            - cd /tmp;
              wget -q https://github.com/fullstorydev/grpcurl/releases/download/v1.8.2/grpcurl_1.8.2_linux_arm64.tar.gz;
              tar xvfz grpcurl_1.8.2_linux_arm64.tar.gz;
              /tmp/grpcurl -plaintext alert.core.svc.cluster.local:8004 core.alert.AlertService.AnalyzeAlertAll;
          restartPolicy: Never
