apiVersion: v1
kind: Service
metadata:
  name: alert
  namespace: core
  labels:
    app: alert
spec:
  clusterIP: None
  selector:
    app: alert
  ports:
    - name: alert
      protocol: TCP
      port: 8004
      targetPort: 8004
