apiVersion: v1
kind: Service
metadata:
  name: iam
  namespace: core
  labels:
    app: iam
spec:
  clusterIP: None
  selector:
    app: iam
  ports:
    - name: iam
      protocol: TCP
      port: 8002
      targetPort: 8002
