apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-portscan
  namespace: datasource
  labels:
    app: aws-portscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-portscan
  template:
    metadata:
      labels:
        app: aws-portscan
    spec:
      serviceAccountName: datasource
      containers:
        - name: aws-portscan
          image: 'public.ecr.aws/risken/aws/portscan:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 500m
            requests:
              memory: 200Mi
              cpu: 300m
          ports:
            - containerPort: 9006
              name: portscan
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/aws/portscan'
