apiVersion: v1
kind: Service
metadata:
  name: queue
  namespace: middleware
  labels:
    app: queue
spec:
  clusterIP: None
  selector:
    app: queue
  ports:
    - name: queue
      protocol: TCP
      port: 9324
      targetPort: 9324
    - name: stats
      protocol: TCP
      port: 9325
      targetPort: 9325
