apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-dependency
  namespace: risken
  labels:
    app: code-dependency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-dependency
  template:
    metadata:
      labels:
        app: code-dependency
    spec:
      serviceAccountName: risken
      containers:
        - name: code-dependency
          image: 'public.ecr.aws/risken/code/dependency:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 1
            requests:
              memory: 200Mi
              cpu: 600m
          ports:
            - containerPort: 10003
              name: dependency
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/code/dependency'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
