apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-accessanalyzer
  namespace: datasource
  labels:
    app: aws-accessanalyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-accessanalyzer
  template:
    metadata:
      labels:
        app: aws-accessanalyzer
    spec:
      serviceAccountName: datasource
      containers:
        - name: aws-accessanalyzer
          image: 'public.ecr.aws/risken/aws/access-analyzer:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 9003
              name: accessanalyzer
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/aws/accessanalyzer'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
