apiVersion: v1
kind: Service
metadata:
  name: activity
  namespace: aws
  labels:
    app: activity
spec:
  clusterIP: None
  selector:
    app: activity
  ports:
    - name: activity
      protocol: TCP
      port: 9007
      targetPort: 9007
