apiVersion: apps/v1
kind: Deployment
metadata:
  name: osint-website
  namespace: risken
  labels:
    app: osint-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osint-website
  template:
    metadata:
      labels:
        app: osint-website
    spec:
      serviceAccountName: risken
      containers:
        - name: osint-website
          image: 'public.ecr.aws/risken/osint/website:latest'
          resources:
            limits:
              memory: 300Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 18084
              name: website
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/osint/website'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
