resources:
  # gateway
  - gateway/namespace.yaml
  - gateway/serviceaccount.yaml
  - gateway/gateway/service.yaml
  - gateway/gateway/deployment.yaml
  - gateway/web/service.yaml
  - gateway/web/deployment.yaml

  # core
  - core/namespace.yaml
  - core/serviceaccount.yaml
  - core/cronjob.yaml
  - core/service.yaml
  - core/deployment.yaml

  # datasource
  - datasource/namespace.yaml
  - datasource/serviceaccount.yaml
  - datasource/cronjob.yaml
  ## API
  - datasource/api/service.yaml
  - datasource/api/deployment.yaml
  ## AWS
  - datasource/aws/guardduty/deployment.yaml
  - datasource/aws/accessanalyzer/deployment.yaml
  - datasource/aws/adminchecker/deployment.yaml
  - datasource/aws/cloudsploit/deployment.yaml
  - datasource/aws/portscan/deployment.yaml
  ## Code
  - datasource/code/dependency/deployment.yaml
  - datasource/code/gitleaks/deployment.yaml
  - datasource/code/codescan/deployment.yaml
  ## Diagnosis
  - datasource/diagnosis/applicationscan/deployment.yaml
  - datasource/diagnosis/portscan/deployment.yaml
  - datasource/diagnosis/wpscan/deployment.yaml
  ## Google
  - datasource/google/asset/deployment.yaml
  - datasource/google/cloudsploit/deployment.yaml
  - datasource/google/portscan/deployment.yaml
  - datasource/google/scc/deployment.yaml
  ## OSINT
  - datasource/osint/subdomain/deployment.yaml
  - datasource/osint/website/deployment.yaml
