resources:
  # gateway
  - gateway/namespace.yaml
  - gateway/serviceaccount.yaml
  - gateway/gateway/service.yaml
  - gateway/gateway/deployment.yaml
  - gateway/web/service.yaml
  - gateway/web/deployment.yaml

  # core
  - core/namespace.yaml
  - core/serviceaccount.yaml
  - core/cronjob.yaml
  - core/service.yaml
  - core/deployment.yaml

  # aws
  - aws/namespace.yaml
  - aws/serviceaccount.yaml
  - aws/guardduty/deployment.yaml
  - aws/accessanalyzer/deployment.yaml
  - aws/adminchecker/deployment.yaml
  - aws/cloudsploit/deployment.yaml
  - aws/portscan/deployment.yaml
  - aws/activity/service.yaml
  - aws/activity/deployment.yaml

  # osint
  - osint/namespace.yaml
  - osint/serviceaccount.yaml
  - osint/subdomain/deployment.yaml
  - osint/website/deployment.yaml

  # diagnosis
  - diagnosis/namespace.yaml
  - diagnosis/serviceaccount.yaml
  - diagnosis/wpscan/deployment.yaml
  - diagnosis/portscan/deployment.yaml
  - diagnosis/applicationscan/deployment.yaml
  
  # code
  - code/namespace.yaml
  - code/serviceaccount.yaml
  - code/gitleaks/deployment.yaml

  # google
  - google/namespace.yaml
  - google/serviceaccount.yaml
  - google/asset/deployment.yaml
  - google/cloudsploit/deployment.yaml
  - google/scc/deployment.yaml
  - google/portscan/deployment.yaml
