apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high
value: 100
globalDefault: false

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low
value: 10
globalDefault: false
