apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-cronjob
  namespace: aws
  labels:
    app: aws
spec:
  # The time zone must be set in UTC.(For JST, set +0900)
  # @see https://kubernetes.io/ja/docs/concepts/workloads/controllers/cron-jobs/ 
  schedule: "00 17 * * *" 
  jobTemplate:
    metadata:
      labels:
        app: aws
    spec:
      template:
        spec:
          serviceAccountName: aws
          containers:
          - name: aws-cronjob
            image: alpine
            resources:
              limits:
                memory: 400Mi
                cpu: 200m
              requests:
                memory: 200Mi
                cpu: 100m
            command: ["sh", "-c"]
            args:
            - cd /tmp;
              wget -q https://github.com/fullstorydev/grpcurl/releases/download/v1.8.2/grpcurl_1.8.2_linux_arm64.tar.gz;
              tar xvfz grpcurl_1.8.2_linux_arm64.tar.gz;
              /tmp/grpcurl -plaintext aws.aws.svc.cluster.local:9001 aws.aws.AWSService.InvokeScanAll;
          restartPolicy: Never
