apiVersion: v1
kind: Service
metadata:
  name: aws
  namespace: aws
  labels:
    app: aws
spec:
  clusterIP: None
  selector:
    app: aws
  ports:
    - name: aws
      protocol: TCP
      port: 9001
      targetPort: 9001
