apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-portscan
  namespace: risken
  labels:
    app: google-portscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-portscan
  template:
    metadata:
      labels:
        app: google-portscan
    spec:
      serviceAccountName: risken
      containers:
        - name: google-portscan
          image: 'public.ecr.aws/risken/google/portscan:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 11005
              name: portscan
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/google/portscan'
