apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-prowler
  namespace: risken
  labels:
    app: azure-prowler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-prowler
  template:
    metadata:
      labels:
        app: azure-prowler
    spec:
      serviceAccountName: risken
      containers:
        - name: azure-prowler
          image: 'public.ecr.aws/risken/azure/prowler:latest'
          resources:
            limits:
              memory: 400Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 12001
              name: prowler
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/azure/prowler'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
