apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-cloudsploit
  namespace: datasource
  labels:
    app: google-cloudsploit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-cloudsploit
  template:
    metadata:
      labels:
        app: google-cloudsploit
    spec:
      serviceAccountName: datasource
      containers:
        - name: google-cloudsploit
          image: 'public.ecr.aws/risken/google/cloudsploit:latest'
          resources:
            limits:
              memory: 800Mi
              cpu: 1
            requests:
              memory: 500Mi
              cpu: 600m
          ports:
            - containerPort: 11003
              name: cloudsploit
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/google/cloudsploit'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
