apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationscan
  namespace: diagnosis
  labels:
    app: applicationscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationscan
  template:
    metadata:
      labels:
        app: applicationscan
    spec:
      serviceAccountName: diagnosis
      containers:
        - name: applicationscan
          image: 'public.ecr.aws/risken/diagnosis/applicationscan:latest'
          resources:
            limits:
              memory: 600Mi
              cpu: 300m
            requests:
              memory: 400Mi
              cpu: 200m
          ports:
            - containerPort: 19005
              name: applicationscan
          env:
            - name: AWS_DEFAULT_REGION
              value: 'region-code'
            - name: AWS_XRAY_SDK_DISABLED
              value: 'TRUE'
            - name: AWS_XRAY_CONTEXT_MISSING
              value: 'LOG_ERROR'
            - name: ENV_INJECTOR_META_CONFIG
              value: '/env/meta/diagnosis/applicationscan'
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
               - all
